allowBuilds:
    "@alicloud/openapi-core": true
    "@prisma/engines": true
    better-sqlite3: true
    prisma: true
    sharp: true
    unrs-resolver: true

minimumReleaseAgeExclude:
    - deepsea-tools
    - sdnext
    - soda-antd
    - soda-hooks
    - soda-next
    - soda-tailwind
    - soda-tanstack-query
    - soda-react
