allowBuilds:
    "@alicloud/openapi-core": true
    "@prisma/engines": true
    better-sqlite3: true
    core-js: false
    prisma: true
    sharp: true
    unrs-resolver: true

minimumReleaseAgeExclude:
    - "@1adybug/eslint"
    - "@1adybug/prettier"
    - "@1adybug/prettier-plugin-block-padding"
    - "@1adybug/prettier-plugin-remove-braces"
    - "@1adybug/prettier-plugin-sort-imports"
    - "@1adybug/xlsx"
    - deepsea-components
    - deepsea-tools
    - sdnext
    - soda-hooks
    - soda-next
    - soda-tanstack-query
    - soda-react
    - soda-type
