-- CreateTable
CREATE TABLE "Certificate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "days" INTEGER NOT NULL DEFAULT 3650,
    "certificatePath" TEXT NOT NULL,
    "certificateKeyPath" TEXT NOT NULL,
    "expiresAt" DATETIME NOT NULL,
    "remark" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "Certificate_address_key" ON "Certificate"("address");

-- CreateIndex
CREATE INDEX "Certificate_address_idx" ON "Certificate"("address");

-- Preserve certificates that were generated by proxy services before certificates became reusable resources.
INSERT OR IGNORE INTO "Certificate" (
    "id",
    "createdAt",
    "updatedAt",
    "name",
    "address",
    "days",
    "certificatePath",
    "certificateKeyPath",
    "expiresAt",
    "remark"
)
SELECT
    "id",
    "createdAt",
    "updatedAt",
    COALESCE(NULLIF("sourceAddress", ''), "targetHost", "id"),
    COALESCE(NULLIF("sourceAddress", ''), "targetHost", "id"),
    "certificateDays",
    COALESCE("certificatePath", '/app/data/nginx/certs/' || "id" || '.crt'),
    COALESCE("certificateKeyPath", '/app/data/nginx/certs/' || "id" || '.key'),
    COALESCE("certificateExpiresAt", datetime('now', '+' || "certificateDays" || ' days')),
    "remark"
FROM "ProxyService"
WHERE "httpsEnabled" = true;

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ProxyService" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "serviceType" TEXT NOT NULL DEFAULT 'reverseProxy',
    "sourceAddress" TEXT NOT NULL,
    "httpPort" INTEGER NOT NULL DEFAULT 80,
    "httpsPort" INTEGER NOT NULL DEFAULT 443,
    "targetProtocol" TEXT NOT NULL DEFAULT 'http',
    "targetHost" TEXT NOT NULL,
    "targetPort" INTEGER NOT NULL,
    "locations" JSONB NOT NULL DEFAULT '[]',
    "websocketEnabled" BOOLEAN NOT NULL DEFAULT true,
    "tcpForwardEnabled" BOOLEAN NOT NULL DEFAULT true,
    "udpForwardEnabled" BOOLEAN NOT NULL DEFAULT false,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "httpsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "http2HttpsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "certificateId" TEXT,
    "lastAppliedAt" DATETIME,
    "lastApplyError" TEXT,
    "remark" TEXT,
    CONSTRAINT "ProxyService_certificateId_fkey" FOREIGN KEY ("certificateId") REFERENCES "Certificate" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_ProxyService" (
    "createdAt",
    "enabled",
    "http2HttpsEnabled",
    "httpPort",
    "httpsEnabled",
    "httpsPort",
    "id",
    "lastAppliedAt",
    "lastApplyError",
    "locations",
    "remark",
    "serviceType",
    "sourceAddress",
    "targetHost",
    "targetPort",
    "targetProtocol",
    "tcpForwardEnabled",
    "udpForwardEnabled",
    "updatedAt",
    "websocketEnabled",
    "certificateId"
)
SELECT
    "createdAt",
    "enabled",
    "http2HttpsEnabled",
    "httpPort",
    "httpsEnabled",
    "httpsPort",
    "id",
    "lastAppliedAt",
    "lastApplyError",
    "locations",
    "remark",
    "serviceType",
    CASE
        WHEN "httpsEnabled" = true THEN COALESCE(NULLIF("sourceAddress", ''), "targetHost", "id")
        ELSE "sourceAddress"
    END,
    "targetHost",
    "targetPort",
    "targetProtocol",
    "tcpForwardEnabled",
    "udpForwardEnabled",
    "updatedAt",
    "websocketEnabled",
    (
        SELECT "Certificate"."id"
        FROM "Certificate"
        WHERE "Certificate"."address" = COALESCE(NULLIF("ProxyService"."sourceAddress", ''), "ProxyService"."targetHost", "ProxyService"."id")
        LIMIT 1
    )
FROM "ProxyService";
DROP TABLE "ProxyService";
ALTER TABLE "new_ProxyService" RENAME TO "ProxyService";
CREATE INDEX "ProxyService_sourceAddress_idx" ON "ProxyService"("sourceAddress");
CREATE INDEX "ProxyService_targetHost_idx" ON "ProxyService"("targetHost");
CREATE INDEX "ProxyService_certificateId_idx" ON "ProxyService"("certificateId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
